const quotes = [
            {
                "id": 1,
                "quote_text": "If you can't love yourself, how in the hell you gonna love somebody else?",
                "created_at": "2023-01-15T09:30:00Z",
                "series": 1,
                "season": 6,
                "episode": 1,
                "timestamp": "00:12:45",
                "speaker": "RuPaul",
                "context": "Opening message",
                "user_id": "admin01",
                "image_url": "/images/rupaul-s6e1.jpg",
                "is_approved": true,
                "vote_count": 2845,
                "tags": ["love", "inspirational"]
            },
            {
                "id": 2,
                "quote_text": "Miss Vanjie... Miss Vanjie... Miss... Vanjie...",
                "created_at": "2023-01-16T11:20:00Z",
                "Series": 2,
                "season": 10,
                "episode": 1,
                "timestamp": "00:42:30",
                "speaker": "Vanessa Vanjie Mateo",
                "context": "Elimination exit",
                "user_id": "editor02",
                "image_url": "/images/vanjie-s10e1.gif",
                "is_approved": true,
                "vote_count": 2317,
                "tags": ["meme", "elimination"]
            },
            {
                "id": 3,
                "quote_text": "The shade... the shade of it all!",
                "created_at": "2023-01-17T14:15:00Z",
                "season": 4,
                "episode": 3,
                "timestamp": "00:28:12",
                "speaker": "Shangela",
                "context": "Untucked argument",
                "user_id": "contributor05",
                "image_url": "/images/shangela-s4e3.png",
                "is_approved": true,
                "vote_count": 1892,
                "tags": ["drama", "untucked"]
            },
            {
                "id": 4,
                "quote_text": "I'm not joking, bitch!",
                "created_at": "2023-01-18T10:45:00Z",
                "season": 2,
                "episode": 5,
                "timestamp": "00:35:22",
                "speaker": "Tatianna",
                "context": "Argument with Tyra Sanchez",
                "user_id": "moderator03",
                "image_url": "/images/tatianna-s2e5.jpg",
                "is_approved": true,
                "vote_count": 1678,
                "tags": ["argument", "iconic"]
            },
            {
                "id": 5,
                "quote_text": "Back rolls?!",
                "created_at": "2023-01-19T08:20:00Z",
                "season": 5,
                "episode": 2,
                "timestamp": "00:18:45",
                "speaker": "Alyssa Edwards",
                "context": "Reading challenge",
                "user_id": "editor02",
                "image_url": "/images/alyssa-s5e2.gif",
                "is_approved": true,
                "vote_count": 2456,
                "tags": ["reading", "meme"]
            },
            {
                "id": 6,
                "quote_text": "Choices...",
                "created_at": "2023-01-20T13:10:00Z",
                "season": 10,
                "episode": 7,
                "timestamp": "00:52:18",
                "speaker": "Asia O'Hara",
                "context": "Reacting to runway looks",
                "user_id": "contributor07",
                "image_url": "/images/asia-s10e7.jpg",
                "is_approved": true,
                "vote_count": 1324,
                "tags": ["reaction", "sassy"]
            },
            {
                "id": 7,
                "quote_text": "This is not RuPaul's Best Friend Race!",
                "created_at": "2023-01-21T16:30:00Z",
                "season": 4,
                "episode": 1,
                "timestamp": "00:25:10",
                "speaker": "RuPaul",
                "context": "Main stage judging",
                "user_id": "admin01",
                "image_url": "/images/rupaul-s4e1.jpg",
                "is_approved": true,
                "vote_count": 987,
                "tags": ["judging", "competition"]
            },
            {
                "id": 8,
                "quote_text": "Your tone seems very pointed right now.",
                "created_at": "2023-01-22T11:15:00Z",
                "season": 4,
                "episode": 8,
                "timestamp": "00:44:33",
                "speaker": "Latrice Royale",
                "context": "Untucked argument",
                "user_id": "moderator04",
                "image_url": "/images/latrice-s4e8.png",
                "is_approved": true,
                "vote_count": 2103,
                "tags": ["argument", "untucked"]
            },
            {
                "id": 9,
                "quote_text": "I feel very attacked!",
                "created_at": "2023-01-23T14:20:00Z",
                "season": 6,
                "episode": 4,
                "timestamp": "00:39:47",
                "speaker": "Laganja Estranja",
                "context": "Untucked breakdown",
                "user_id": "contributor09",
                "image_url": "/images/laganja-s6e4.gif",
                "is_approved": true,
                "vote_count": 2765,
                "tags": ["meme", "drama"]
            },
            {
                "id": 10,
                "quote_text": "Come on, Season 6, let's get sickening!",
                "created_at": "2023-01-24T09:45:00Z",
                "season": 6,
                "episode": 1,
                "timestamp": "00:15:22",
                "speaker": "Courtney Act",
                "context": "Entrance line",
                "user_id": "editor02",
                "image_url": "/images/courtney-s6e1.jpg",
                "is_approved": true,
                "vote_count": 876,
                "tags": ["entrance", "catchphrase"]
            },
            {
                "id": 11,
                "quote_text": "Water off a duck's back.",
                "created_at": "2023-01-25T12:30:00Z",
                "season": 2,
                "episode": 3,
                "timestamp": "00:31:15",
                "speaker": "Jujubee",
                "context": "Untucked advice",
                "user_id": "moderator05",
                "image_url": "/images/jujubee-s2e3.jpg",
                "is_approved": true,
                "vote_count": 1543,
                "tags": ["advice", "untucked"]
            },
            {
                "id": 12,
                "quote_text": "I'm the boom boom Gunn",
                "created_at": "2023-01-26T10:10:00Z",
                "season": 3,
                "episode": 2,
                "timestamp": "00:22:40",
                "speaker": "Mimi Imfurst",
                "context": "Workroom introduction",
                "user_id": "contributor11",
                "image_url": "/images/mimi-s3e2.jpg",
                "is_approved": true,
                "vote_count": 765,
                "tags": ["introduction", "catchphrase"]
            },
            {
                "id": 13,
                "quote_text": "Party!",
                "created_at": "2023-01-27T15:25:00Z",
                "season": 7,
                "episode": 1,
                "timestamp": "00:17:55",
                "speaker": "Adore Delano",
                "context": "Entrance line",
                "user_id": "editor03",
                "image_url": "/images/adore-s7e1.gif",
                "is_approved": true,
                "vote_count": 1432,
                "tags": ["entrance", "iconic"]
            },
            {
                "id": 14,
                "quote_text": "Not today, Satan!",
                "created_at": "2023-01-28T11:40:00Z",
                "season": 5,
                "episode": 6,
                "timestamp": "00:48:12",
                "speaker": "Bianca Del Rio",
                "context": "Reading challenge",
                "user_id": "admin01",
                "image_url": "/images/bianca-s5e6.jpg",
                "is_approved": true,
                "vote_count": 1987,
                "tags": ["reading", "catchphrase"]
            },
            {
                "id": 15,
                "quote_text": "Halleloo!",
                "created_at": "2023-01-29T14:50:00Z",
                "season": 2,
                "episode": 1,
                "timestamp": "00:13:25",
                "speaker": "Shangela",
                "context": "Entrance line",
                "user_id": "contributor15",
                "image_url": "/images/shangela-s2e1.png",
                "is_approved": true,
                "vote_count": 1765,
                "tags": ["entrance", "catchphrase"]
            },
            {
                "id": 16,
                "quote_text": "Henny...",
                "created_at": "2023-01-30T09:15:00Z",
                "season": 3,
                "episode": 4,
                "timestamp": "00:36:18",
                "speaker": "Stacy Layne Matthews",
                "context": "Workroom conversation",
                "user_id": "moderator06",
                "image_url": "/images/stacy-s3e4.jpg",
                "is_approved": true,
                "vote_count": 1234,
                "tags": ["meme", "workroom"]
            },
            {
                "id": 17,
                "quote_text": "I don't get cute, I get drop-dead gorgeous.",
                "created_at": "2023-01-31T13:20:00Z",
                "season": 3,
                "episode": 1,
                "timestamp": "00:19:30",
                "speaker": "Raja",
                "context": "Entrance line",
                "user_id": "editor04",
                "image_url": "/images/raja-s3e1.jpg",
                "is_approved": true,
                "vote_count": 1432,
                "tags": ["entrance", "confidence"]
            },
            {
                "id": 18,
                "quote_text": "What do you do successfully? Quickly.",
                "created_at": "2023-02-01T10:05:00Z",
                "season": 5,
                "episode": 3,
                "timestamp": "00:27:45",
                "speaker": "Alyssa Edwards",
                "context": "Reading challenge",
                "user_id": "contributor18",
                "image_url": "/images/alyssa-s5e3.gif",
                "is_approved": true,
                "vote_count": 1654,
                "tags": ["reading", "sassy"]
            },
            {
                "id": 19,
                "quote_text": "I'm Roxxxy Andrews and I'm here to make it clear...",
                "created_at": "2023-02-02T14:35:00Z",
                "season": 5,
                "episode": 1,
                "timestamp": "00:16:50",
                "speaker": "Roxxxy Andrews",
                "context": "Entrance line",
                "user_id": "moderator07",
                "image_url": "/images/roxxxy-s5e1.jpg",
                "is_approved": true,
                "vote_count": 987,
                "tags": ["entrance", "catchphrase"]
            },
            {
                "id": 20,
                "quote_text": "Sickening, no?",
                "created_at": "2023-02-03T11:25:00Z",
                "season": 4,
                "episode": 2,
                "timestamp": "00:33:15",
                "speaker": "Sharon Needles",
                "context": "Runway presentation",
                "user_id": "admin01",
                "image_url": "/images/sharon-s4e2.jpg",
                "is_approved": true,
                "vote_count": 876,
                "tags": ["runway", "catchphrase"]
            },
            {
                "id": 21,
                "quote_text": "I'm a fucking libra!",
                "created_at": "2023-02-04T15:40:00Z",
                "season": 9,
                "episode": 1,
                "timestamp": "00:14:22",
                "speaker": "Aja",
                "context": "Entrance line",
                "user_id": "contributor22",
                "image_url": "/images/aja-s9e1.gif",
                "is_approved": true,
                "vote_count": 1432,
                "tags": ["entrance", "meme"]
            },
            {
                "id": 22,
                "quote_text": "Oh, Jesus, gross.",
                "created_at": "2023-02-05T10:15:00Z",
                "season": 7,
                "episode": 4,
                "timestamp": "00:41:30",
                "speaker": "Katya",
                "context": "Reacting to runway look",
                "user_id": "editor05",
                "image_url": "/images/katya-s7e4.jpg",
                "is_approved": true,
                "vote_count": 1987,
                "tags": ["reaction", "funny"]
            },
            {
                "id": 23,
                "quote_text": "I'm a messy bitch who lives for drama.",
                "created_at": "2023-02-06T13:50:00Z",
                "season": 8,
                "episode": 1,
                "timestamp": "00:18:45",
                "speaker": "Bob the Drag Queen",
                "context": "Entrance line",
                "user_id": "moderator08",
                "image_url": "/images/bob-s8e1.jpg",
                "is_approved": true,
                "vote_count": 1765,
                "tags": ["entrance", "honest"]
            },
            {
                "id": 24,
                "quote_text": "The library is open!",
                "created_at": "2023-02-07T09:30:00Z",
                "season": 4,
                "episode": 5,
                "timestamp": "00:25:10",
                "speaker": "RuPaul",
                "context": "Reading challenge announcement",
                "user_id": "admin01",
                "image_url": "/images/rupaul-s4e5.jpg",
                "is_approved": true,
                "vote_count": 1543,
                "tags": ["reading", "challenge"]
            },
            {
                "id": 25,
                "quote_text": "I'm acting!",
                "created_at": "2023-02-08T14:20:00Z",
                "season": 5,
                "episode": 7,
                "timestamp": "00:39:45",
                "speaker": "Detox",
                "context": "Untucked argument",
                "user_id": "contributor25",
                "image_url": "/images/detox-s5e7.gif",
                "is_approved": true,
                "vote_count": 1321,
                "tags": ["drama", "untucked"]
            },
            {
                "id": 26,
                "quote_text": "Absolutelyyyyy!",
                "created_at": "2023-02-09T11:10:00Z",
                "season": 6,
                "episode": 2,
                "timestamp": "00:22:30",
                "speaker": "Gia Gunn",
                "context": "Workroom conversation",
                "user_id": "editor06",
                "image_url": "/images/gia-s6e2.jpg",
                "is_approved": true,
                "vote_count": 1098,
                "tags": ["meme", "workroom"]
            },
            {
                "id": 27,
                "quote_text": "I'm not a regular mom, I'm a cool mom!",
                "created_at": "2023-02-10T15:30:00Z",
                "season": 7,
                "episode": 3,
                "timestamp": "00:35:15",
                "speaker": "Ginger Minj",
                "context": "Snatch Game",
                "user_id": "moderator09",
                "image_url": "/images/ginger-s7e3.jpg",
                "is_approved": true,
                "vote_count": 1432,
                "tags": ["snatch-game", "funny"]
            },
            {
                "id": 28,
                "quote_text": "Life's not fair!",
                "created_at": "2023-02-11T10:45:00Z",
                "season": 5,
                "episode": 8,
                "timestamp": "00:47:22",
                "speaker": "Jinkx Monsoon",
                "context": "Lip sync motivation",
                "user_id": "admin01",
                "image_url": "/images/jinkx-s5e8.jpg",
                "is_approved": true,
                "vote_count": 1210,
                "tags": ["lip-sync", "inspirational"]
            },
            {
                "id": 29,
                "quote_text": "I'm a professional!",
                "created_at": "2023-02-12T13:15:00Z",
                "season": 6,
                "episode": 5,
                "timestamp": "00:28:40",
                "speaker": "Courtney Act",
                "context": "Workroom conversation",
                "user_id": "contributor29",
                "image_url": "/images/courtney-s6e5.jpg",
                "is_approved": true,
                "vote_count": 876,
                "tags": ["workroom", "confidence"]
            },
            {
                "id": 30,
                "quote_text": "Drag is not a contact sport!",
                "created_at": "2023-02-13T09:50:00Z",
                "season": 9,
                "episode": 4,
                "timestamp": "00:42:15",
                "speaker": "RuPaul",
                "context": "Main stage warning",
                "user_id": "editor07",
                "image_url": "/images/rupaul-s9e4.jpg",
                "is_approved": true,
                "vote_count": 987,
                "tags": ["judging", "warning"]
            },
            {
                "id": 31,
                "quote_text": "I'm a glamazon bitch ready for the runway!",
                "created_at": "2023-02-14T14:25:00Z",
                "season": 4,
                "episode": 1,
                "timestamp": "00:14:30",
                "speaker": "Chad Michaels",
                "context": "Entrance line",
                "user_id": "moderator10",
                "image_url": "/images/chad-s4e1.jpg",
                "is_approved": true,
                "vote_count": 765,
                "tags": ["entrance", "confidence"]
            },
            {
                "id": 32,
                "quote_text": "She done already done had herses!",
                "created_at": "2023-02-15T11:35:00Z",
                "season": 6,
                "episode": 1,
                "timestamp": "00:10:15",
                "speaker": "RuPaul",
                "context": "Opening credits",
                "user_id": "admin01",
                "image_url": "/images/rupaul-s6e1-credits.jpg",
                "is_approved": true,
                "vote_count": 1543,
                "tags": ["opening", "catchphrase"]
            },
            {
                "id": 33,
                "quote_text": "I'm a strong, independent woman!",
                "created_at": "2023-02-16T15:00:00Z",
                "season": 5,
                "episode": 4,
                "timestamp": "00:33:45",
                "speaker": "Coco Montrese",
                "context": "Untucked argument",
                "user_id": "contributor33",
                "image_url": "/images/coco-s5e4.gif",
                "is_approved": true,
                "vote_count": 1098,
                "tags": ["drama", "untucked"]
            },
            {
                "id": 34,
                "quote_text": "I'm a fucking professional!",
                "created_at": "2023-02-17T10:20:00Z",
                "season": 9,
                "episode": 6,
                "timestamp": "00:45:10",
                "speaker": "Valentina",
                "context": "Lip sync meltdown",
                "user_id": "editor08",
                "image_url": "/images/valentina-s9e6.gif",
                "is_approved": true,
                "vote_count": 1987,
                "tags": ["lip-sync", "meme"]
            },
            {
                "id": 35,
                "quote_text": "I'm a fucking star, bitch!",
                "created_at": "2023-02-18T13:40:00Z",
                "season": 10,
                "episode": 1,
                "timestamp": "00:16:25",
                "speaker": "Monét X Change",
                "context": "Entrance line",
                "user_id": "moderator11",
                "image_url": "/images/monet-s10e1.jpg",
                "is_approved": true,
                "vote_count": 1432,
                "tags": ["entrance", "confidence"]
            },
            {
                "id": 36,
                "quote_text": "I'm not a bitch, I'm THE bitch!",
                "created_at": "2023-02-19T09:55:00Z",
                "season": 8,
                "episode": 2,
                "timestamp": "00:24:30",
                "speaker": "Derrick Barry",
                "context": "Workroom conversation",
                "user_id": "admin01",
                "image_url": "/images/derrick-s8e2.jpg",
                "is_approved": true,
                "vote_count": 1210,
                "tags": ["workroom", "confidence"]
            },
            {
                "id": 37,
                "quote_text": "I'm a whole damn meal!",
                "created_at": "2023-02-20T14:15:00Z",
                "season": 11,
                "episode": 1,
                "timestamp": "00:15:45",
                "speaker": "Silky Nutmeg Ganache",
                "context": "Entrance line",
                "user_id": "contributor37",
                "image_url": "/images/silky-s11e1.gif",
                "is_approved": true,
                "vote_count": 1098,
                "tags": ["entrance", "confidence"]
            },
            {
                "id": 38,
                "quote_text": "I'm the trade of the season!",
                "created_at": "2023-02-21T11:25:00Z",
                "season": 9,
                "episode": 1,
                "timestamp": "00:17:10",
                "speaker": "Peppermint",
                "context": "Entrance line",
                "user_id": "editor09",
                "image_url": "/images/peppermint-s9e1.jpg",
                "is_approved": true,
                "vote_count": 876,
                "tags": ["entrance", "confidence"]
            },
            {
                "id": 39,
                "quote_text": "I'm a fucking winner, baby!",
                "created_at": "2023-02-22T15:35:00Z",
                "season": 6,
                "episode": 12,
                "timestamp": "01:02:45",
                "speaker": "Bianca Del Rio",
                "context": "Crowning moment",
                "user_id": "moderator12",
                "image_url": "/images/bianca-s6e12.jpg",
                "is_approved": true,
                "vote_count": 1543,
                "tags": ["winner", "finale"]
            },
            {
                "id": 40,
                "quote_text": "I'm a fucking drag queen!",
                "created_at": "2023-02-23T10:40:00Z",
                "season": 7,
                "episode": 6,
                "timestamp": "00:38:15",
                "speaker": "Kennedy Davenport",
                "context": "Untucked argument",
                "user_id": "admin01",
                "image_url": "/images/kennedy-s7e6.gif",
                "is_approved": true,
                "vote_count": 1321,
                "tags": ["drama", "untucked"]
            },
            {
                "id": 41,
                "quote_text": "I'm a fucking All Star!",
                "created_at": "2023-02-24T13:55:00Z",
                "season": 2,
                "episode": 1,
                "timestamp": "00:12:30",
                "speaker": "Shangela",
                "context": "All Stars 3 entrance",
                "user_id": "contributor41",
                "image_url": "/images/shangela-as3e1.jpg",
                "is_approved": true,
                "vote_count": 1098,
                "tags": ["entrance", "all-stars"]
            },
            {
                "id": 42,
                "quote_text": "I'm a fucking legend!",
                "created_at": "2023-02-25T09:10:00Z",
                "season": 12,
                "episode": 1,
                "timestamp": "00:18:45",
                "speaker": "Heidi N Closet",
                "context": "Entrance line",
                "user_id": "editor10",
                "image_url": "/images/heidi-s12e1.jpg",
                "is_approved": true,
                "vote_count": 987,
                "tags": ["entrance", "confidence"]
            },
            {
                "id": 43,
                "quote_text": "I'm a fucking showgirl!",
                "created_at": "2023-02-26T14:20:00Z",
                "season": 9,
                "episode": 2,
                "timestamp": "00:26:30",
                "speaker": "Eureka",
                "context": "Workroom conversation",
                "user_id": "moderator13",
                "image_url": "/images/eureka-s9e2.jpg",
                "is_approved": true,
                "vote_count": 765,
                "tags": ["workroom", "confidence"]
            },
            {
                "id": 44,
                "quote_text": "I'm a fucking icon!",
                "created_at": "2023-02-27T11:30:00Z",
                "season": 10,
                "episode": 3,
                "timestamp": "00:32:45",
                "speaker": "Kameron Michaels",
                "context": "Untucked conversation",
                "user_id": "admin01",
                "image_url": "/images/kameron-s10e3.jpg",
                "is_approved": true,
                "vote_count": 876,
                "tags": ["untucked", "confidence"]
            },
            {
                "id": 45,
                "quote_text": "I'm a fucking queen!",
                "created_at": "2023-02-28T15:40:00Z",
                "season": 11,
                "episode": 4,
                "timestamp": "00:41:15",
                "speaker": "Yvie Oddly",
                "context": "Runway presentation",
                "user_id": "contributor45",
                "image_url": "/images/yvie-s11e4.jpg",
                "is_approved": true,
                "vote_count": 1098,
                "tags": ["runway", "confidence"]
            },
            {
                "id": 46,
                "quote_text": "I'm a fucking superstar!",
                "created_at": "2023-03-01T10:50:00Z",
                "season": 6,
                "episode": 3,
                "timestamp": "00:29:30",
                "speaker": "Adore Delano",
                "context": "Workroom conversation",
                "user_id": "editor11",
                "image_url": "/images/adore-s6e3.jpg",
                "is_approved": true,
                "vote_count": 765,
                "tags": ["workroom", "confidence"]
            },
            {
                "id": 47,
                "quote_text": "I'm a fucking diva!",
                "created_at": "2023-03-02T14:00:00Z",
                "season": 7,
                "episode": 5,
                "timestamp": "00:35:45",
                "speaker": "Pearl",
                "context": "Untucked conversation",
                "user_id": "moderator14",
                "image_url": "/images/pearl-s7e5.jpg",
                "is_approved": true,
                "vote_count": 654,
                "tags": ["untucked", "confidence"]
            },
            {
                "id": 48,
                "quote_text": "I'm a fucking legend!",
                "created_at": "2023-03-03T11:10:00Z",
                "season": 8,
                "episode": 4,
                "timestamp": "00:38:15",
                "speaker": "Chi Chi DeVayne",
                "context": "Runway presentation",
                "user_id": "admin01",
                "image_url": "/images/chichi-s8e4.jpg",
                "is_approved": true,
                "vote_count": 987,
                "tags": ["runway", "confidence"]
            },
            {
                "id": 49,
                "quote_text": "I'm a fucking winner!",
                "created_at": "2023-03-04T15:20:00Z",
                "season": 9,
                "episode": 14,
                "timestamp": "01:05:30",
                "speaker": "Sasha Velour",
                "context": "Crowning moment",
                "user_id": "contributor49",
                "image_url": "/images/sasha-s9e14.jpg",
                "is_approved": true,
                "vote_count": 1432,
                "tags": ["winner", "finale"]
            },
            {
                "id": 50,
                "quote_text": "I'm a fucking All Stars winner!",
                "created_at": "2023-03-05T10:30:00Z",
                "season": 4,
                "episode": 10,
                "timestamp": "01:12:45",
                "speaker": "Chad Michaels",
                "context": "All Stars 1 crowning",
                "user_id": "editor12",
                "image_url": "/images/chad-as1e10.jpg",
                "is_approved": true,
                "vote_count": 1210,
                "tags": ["winner", "all-stars"]
            }
];

export { quotes }
